// Code generated by options-gen v0.55.3. DO NOT EDIT.

package openai

import (
	fmt461e464ebed9 "fmt"
	"net/http"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	apiKey string,
	model string,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.apiKey = apiKey
	o.model = model

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithClient(opt *http.Client) OptOptionsSetter {
	return func(o *Options) { o.client = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("apiKey", _validate_Options_apiKey(o)))
	errs.Add(errors461e464ebed9.NewValidationError("model", _validate_Options_model(o)))
	errs.Add(errors461e464ebed9.NewValidationError("client", _validate_Options_client(o)))
	return errs.AsError()
}

func _validate_Options_apiKey(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.apiKey, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `apiKey` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_model(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.model, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `model` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_client(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.client, "omitempty"); err != nil {
		return fmt461e464ebed9.Errorf("field `client` did not pass the test: %w", err)
	}
	return nil
}
