package config_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/metalagman/aida/internal/config"
	"github.com/normahq/runtime/agentconfig"
	runtimeconfig "github.com/normahq/runtime/appconfig"
	"github.com/stretchr/testify/require"
)

const openAIMCPUnsupportedError = `provider "openai": agent config schema validation failed: ` +
	`mcp_servers is not supported for type openai`

func TestLoadProfile_DefaultProfileOverlay(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv("HOME", tmpDir)

	path, err := config.ResolveConfigPath()
	require.NoError(t, err)

	err = os.MkdirAll(filepath.Dir(path), 0o700)
	require.NoError(t, err)

	err = os.WriteFile(path, []byte(`runtime:
  providers:
    codex:
      type: codex_acp
      codex_acp:
        model: gpt-5.3-codex
    openai:
      type: openai
      openai:
        api_key: file-key
        model: gpt-4o-mini
aida:
  provider: codex
  mode: confirm
  shell: /bin/sh
profiles:
  default:
    aida:
      provider: openai
`), 0o600)
	require.NoError(t, err)

	cfg, err := config.Load()
	require.NoError(t, err)
	require.Equal(t, "openai", cfg.Aida.Provider)
	require.Equal(t, "confirm", cfg.Aida.Mode)
	require.Equal(t, "/bin/sh", cfg.Aida.Shell)
}

func TestLoadProfile_ExplicitMissingProfileFails(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv("HOME", tmpDir)

	path, err := config.ResolveConfigPath()
	require.NoError(t, err)

	err = os.MkdirAll(filepath.Dir(path), 0o700)
	require.NoError(t, err)

	err = os.WriteFile(path, []byte(`runtime:
  providers:
    codex:
      type: codex_acp
      codex_acp:
        model: gpt-5.3-codex
`), 0o600)
	require.NoError(t, err)

	_, err = config.LoadProfile("missing")
	require.EqualError(t, err, `top-level profile "missing" not found`)
}

func TestConfigRuntimeOverrides(t *testing.T) {
	cfg := &config.Config{
		Runtime: runtimeConfigWithProviders(),
		Aida: config.AidaConfig{
			Provider: "openai",
			Mode:     "confirm",
			Shell:    "/bin/sh",
		},
	}

	err := cfg.SetProviderModel("openai", "gpt-5")
	require.NoError(t, err)
	err = cfg.SetProviderAPIKey("openai", "test-key")
	require.NoError(t, err)

	provider := cfg.Runtime.Providers["openai"]
	require.Equal(t, "gpt-5", provider.OpenAI.Model)
	require.Equal(t, "test-key", provider.OpenAI.APIKey)

	err = cfg.SetProviderAPIKey("codex", "bad")
	require.EqualError(t, err, "--api-key is only supported for openai and aistudio providers")
}

func TestLoadProfile_IgnoresInvalidInactiveProvider(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv("HOME", tmpDir)

	path, err := config.ResolveConfigPath()
	require.NoError(t, err)

	err = os.MkdirAll(filepath.Dir(path), 0o700)
	require.NoError(t, err)

	err = os.WriteFile(path, []byte(`runtime:
  providers:
    codex:
      type: codex_acp
      codex_acp:
        model: gpt-5.3-codex
    openai:
      type: openai
      mcp_servers: [broken]
      openai:
        api_key: test-key
        model: gpt-4o-mini
  mcp_servers:
    broken:
      type: stdio
aida:
  provider: codex
`), 0o600)
	require.NoError(t, err)

	cfg, err := config.Load()
	require.NoError(t, err)
	require.NoError(t, cfg.ValidateSelectedRuntime())
}

func TestLoadProfile_RejectsMalformedOldInitConfig(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv("HOME", tmpDir)

	path, err := config.ResolveConfigPath()
	require.NoError(t, err)

	err = os.MkdirAll(filepath.Dir(path), 0o700)
	require.NoError(t, err)

	err = os.WriteFile(path, []byte(`runtime:
  providers:
    codex:
      type: codex_acp
      codexacp:
        model: gpt-5.3-codex
aida:
  provider: codex
`), 0o600)
	require.NoError(t, err)

	_, err = config.Load()
	require.Error(t, err)
	require.Contains(t, err.Error(), "generated by a buggy version of aida init")
	require.Contains(t, err.Error(), "rerun `aida init --force`")
}

func TestValidateSelectedRuntime_SelectedInvalidProviderFails(t *testing.T) {
	cfg := &config.Config{
		Runtime: runtimeconfig.RuntimeConfig{
			Providers: map[string]agentconfig.Config{
				"openai": {
					Type:       agentconfig.AgentTypeOpenAI,
					MCPServers: []string{"broken"},
					OpenAI: &agentconfig.LocalAPIConfig{
						APIKey: "test-key",
						Model:  "gpt-4o-mini",
					},
				},
			},
		},
		Aida: config.AidaConfig{
			Provider: "openai",
		},
	}

	err := cfg.ValidateSelectedRuntime()
	require.EqualError(t, err, openAIMCPUnsupportedError)
}

func TestValidateSelectedRuntime_SelectedProviderIgnoresInactiveBrokenMCP(t *testing.T) {
	cfg := &config.Config{
		Runtime: runtimeconfig.RuntimeConfig{
			Providers: map[string]agentconfig.Config{
				"codex": {
					Type: agentconfig.AgentTypeCodexACP,
					CodexACP: &agentconfig.ACPConfig{
						Model: "gpt-5.3-codex",
					},
				},
				"custom": {
					Type:       agentconfig.AgentTypeGenericACP,
					MCPServers: []string{"broken"},
					GenericACP: &agentconfig.ACPConfig{
						Cmd: []string{"custom-acp"},
					},
				},
			},
			MCPServers: map[string]agentconfig.MCPServerConfig{
				"broken": {
					Type: agentconfig.MCPServerTypeStdio,
				},
			},
		},
		Aida: config.AidaConfig{
			Provider: "codex",
		},
	}

	require.NoError(t, cfg.ValidateSelectedRuntime())
}

func TestValidateSelectedRuntime_SelectedPoolValidatesMembers(t *testing.T) {
	cfg := &config.Config{
		Runtime: runtimeconfig.RuntimeConfig{
			Providers: map[string]agentconfig.Config{
				"pool": {
					Type: agentconfig.AgentTypePool,
					PoolConfig: &agentconfig.PoolConfig{
						Members: []string{"codex", "openai"},
					},
				},
				"codex": {
					Type: agentconfig.AgentTypeCodexACP,
					CodexACP: &agentconfig.ACPConfig{
						Model: "gpt-5.3-codex",
					},
				},
				"openai": {
					Type:       agentconfig.AgentTypeOpenAI,
					MCPServers: []string{"broken"},
					OpenAI: &agentconfig.LocalAPIConfig{
						APIKey: "test-key",
						Model:  "gpt-4o-mini",
					},
				},
			},
		},
		Aida: config.AidaConfig{
			Provider: "pool",
		},
	}

	err := cfg.ValidateSelectedRuntime()
	require.EqualError(t, err, openAIMCPUnsupportedError)
}

func runtimeConfigWithProviders() runtimeconfig.RuntimeConfig {
	return runtimeconfig.RuntimeConfig{
		Providers: map[string]agentconfig.Config{
			"openai": {
				Type: agentconfig.AgentTypeOpenAI,
				OpenAI: &agentconfig.LocalAPIConfig{
					Model: "gpt-4o-mini",
				},
			},
			"codex": {
				Type: agentconfig.AgentTypeCodexACP,
				CodexACP: &agentconfig.ACPConfig{
					Model: "gpt-5.3-codex",
				},
			},
		},
	}
}
